name: MinimalApp
settings:
  GENERATE_INFOPLIST_FILE: YES
  INFOPLIST_KEY_UILaunchScreen_Generation: YES
packages:
  ScreenshotsTool:
    path: ../..
targets:
  MinimalApp:
    type: application
    platform: iOS
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: io.github.wacumov.screenshots-tool-demo
    sources: MinimalApp
  MinimalAppScreenshots:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: MinimalAppScreenshots
        excludes: [screenshots]
    hostApplication: MinimalApp
    dependencies:
      - target: MinimalApp
      - package: ScreenshotsTool
